### ISSUE TITLE
Assembly of UFL form segfaults unless COFFEE optimisation is disabled

### ISSUE THREAD

**Issue by eikehmueller** [coneoproject/COFFEE#28]
# Summary
The code below assembles the UFL form for the weak divergence operator and build a local matrix representation (LMA). It crashes with a segfault unless the line `#parameters["coffee"]["O2"] = False` is uncommented. The matrix A, which passed as the first argument has dimensions 6 x 18 (it maps from the HDiv space to the DG space). However, looking at the generated kernel .c code, the kernel expects `A[8][20]`.

### Additional comments
* I observed this issue on ARCHER.
* It only seems to happen for higher order spaces, i.e. no segfault if I use the lowest order spaces
* It also goes away if I run with `PYOP2_DEBUG=1`

### Code
```python
from firedrake import *
from firedrake.ffc_interface import compile_form

'''Assemble local matrix representation (LMA) of divergence operator.

    In each cell of the grid assemble the local matrix representation
    of the weak divergence operator

    B = phi*div(w)*dx

    * phi a testfunction in the L2 DG space W3.
    * w is a trialfunction in the horizontal velocity space

    The LMA is realised by building a matrix-valued function based on 
    on DG_0 function space, i.e. in each cell we store a 
    ndof_pressure x ndof_velocity matrix which represents the local matrix.
'''

#parameters["coffee"]["O2"] = False

host_mesh = IcosahedralSphereMesh(1.0,refinement_level=4)
mesh = ExtrudedMesh(host_mesh,
                    layers=4,
                    extrusion_type='radial',
                    layer_height=0.1)

# Build function spaces
U1 = FiniteElement('BDFM',triangle,2)
U2 = FiniteElement('DG',triangle,1)
V0 = FiniteElement('CG',interval,2)
V1 = FiniteElement('DG',interval,1)

W2_elt_h = HDiv(OuterProductElement(U1,V1))
W3_elt = OuterProductElement(U2,V1)

W3 = FunctionSpace(mesh,W3_elt)
W2_h = FunctionSpace(mesh,W2_elt_h)

# Test- and trial-functions
phi_test = TestFunction(W3)
w_trial = TrialFunction(W2_h)

# UFL form for divergence        
ufl_form = phi_test*div(w_trial)*mesh._dx
compiled_form = compile_form(ufl_form, 'ufl_form')[0]
kernel = compiled_form[6]
coords = compiled_form[3]
coefficients = compiled_form[4]
arguments = ufl_form.arguments()

# Number of pressure and velocity dofs
ndof_pressure = arguments[0].cell_node_map().arity
ndof_velocity = arguments[1].cell_node_map().arity

# DG_0 function space
V_lma = FunctionSpace(mesh,'DG',0)
# Represent LMA by matrix-valued function on the DG_0 space
lma_B_h = Function(V_lma, val=op2.Dat(V_lma.node_set**(ndof_pressure*ndof_velocity)))

# Extract kernel arguments for passing to par_loop
args = [lma_B_h.dat(op2.INC, lma_B_h.cell_node_map()[op2.i[0]]), 
        coords.dat(op2.READ, coords.cell_node_map(), flatten=True)]
for c in coefficients:
    args.append(c.dat(op2.READ, c.cell_node_map(), flatten=True))

# Execute kernel over grid to build LMA in each cell
op2.par_loop(kernel,lma_B_h.cell_set, *args)

print lma_B_h.dat.data
```

**Comment by eikehmueller** [comment]
See also issues #14 and #26.

**Comment by FabioLuporini** [comment]
Hi Eike,

I was investigating the issue.

Now, the problem turns out to be the fact that what you're passing to the par_loop is an Arg, not a Mat as "usual" - which is reasonable, because here you are not assembling a global matrix. However, the kernel still has a "local iteration space" - that is, in practice, loops over test and trial functions. COFFEE applies padding because it *expects* PyOP2 to know about this "local iteration space" and, essentially, behind the scenes, tells PyOP2 to increase the size of the buffer array which is passed in. However, here the Arg that you create does not carry with itself the information about the presence of the doubly nested local iteration space. So I believe this is a PyOP2 related missing - @wence-  I think you see what I mean, could you enlighten us ?

**Comment by wence-** [comment]
So we're using (abusing) ffc to assemble LMA matrices.  We get a kernel for a bilinear form and then feed it to a par_loop for a Dat.  Now, this works if the array is not padded due to C's type-punning.  But if the array is padded, pyop2 doesn't know about it (it only applies padding to mats, not dats).

I think the solution is, in general, for COFFEE to apply padding inside the kernel body (as mentioned in #14).  Then pyop2 doesn't need to know about any optimisations coffee does.

**Comment by FabioLuporini** [comment]
That is probably the best way to go, agree, but that requires refactoring host.py quite extensively; it's not going to happen anytime soon

Also, I don't quite agree that is the only problem. It looks to me that local iteration space is a concept orthogonal to that of a Mat (you can have a LIS, for example as in Eike's example, even if you don't need to assemble Mats). So the fact that we are only supporting it for Mats seems to me a bit weird.

**Comment by wence-** [comment]
I disagree.  PyOP2 knows the size of the data it ought to pass in, the problem is that optimisations applied to kernel change that value.  At the moment pyop2 only knows to change the value in the case of matrices.  It could be modified to change the value in the general case, but surely this would go away if #14 is addressed (orthogonal to iteration spaces of any kind).

**Comment by FabioLuporini** [comment]
That's not what I meant, at least not completely. The purpose of iteration spaces is to expose a further source of parallelism. So for example, theoretically, in CUDA you could exploit them. Well, in this case, CUDA would break, because we are not providing the right piece of information. 

I think we have two problems here
- I agree pyop2 should never change the kernel signature - that is, coffee should do everything.
- iteration spaces are not properly used in par loop's Args

**Comment by FabioLuporini** [comment]
@eikehmueller this may now have been fixed, when you have some spare time, could you try running the code? you would have to update both PyOP2 and COFFEE

**Comment by dorugeber** [comment]
Fabio, does the code that Eike supplied at least run locally for you?

**Comment by FabioLuporini** [comment]
@eikehmueller this seems to work on my machine now. Could you try it? Thanks!

**Comment by eikehmueller** [comment]
This now runs without a segfault on my laptop. I'm just in the process of updating my firedrake installation on ARCHER, so haven't tried it there yet.

**Comment by eikehmueller** [comment]
Works on ARCHER as well (tested on 1 core and 1 full node = 24 cores). So does that mean that I can use the higher optimisation level everywhere and don't have to drop down to level 0 as I had to do previously (and how much more performance can I expect)?

**Comment by dorugeber** [comment]
To answer, or rather avoid answering, the last part of your question: it's completely form- and polynomial-degree-dependent.  There are results in the COFFEE paper (http://arxiv.org/abs/1407.0904 or http://dl.acm.org/citation.cfm?id=2687415) across a small range of forms, showing anything from no change to 4x speedup (only at higher polynomial order).  From personal experience, even slowdowns aren't uncommon.  There's basically no way to know apart from just trying it.

Fabio, what environment variables/parameter options should Eike use to benchmark this on ARCHER?

**Comment by FabioLuporini** [comment]
Hi Eike, thanks for trying this.

As for your question. This depends on a number of aspects. The first point is "how much assembly bound is the problem you are running" -- I mean, if you spend most of the time on solve, you probably will not see much difference. If assembly is on the other hand quite significant, then we should see some improvements. 

Important would be to run vector code: coffee applies transformations so as to allow compilers to auto-vectorise the code: in my experience, the intel and cray compilers are pretty smart at this, gcc doesn't like small loops. At the moment, coffee can also explicitly vectorise bilinear forms. However, since this is lma, I guess you're mostly running 1 forms. 

Very near in the future (hope early this coming week), another PR will land in coffee which does something more for 1 forms as well. 

I'm happy to help with this: the crucial question is the first one I wrote, which is if this problem spends a significant % of time in assembly. I'll leave the issue open for the moment so that you can answer.

Thanks!

**Comment by FabioLuporini** [comment]
Andrew: as long as experiments are run in a "meaningful" environment, there should be no slowdowns. If there are, that's because coffee assumes (rightfully) something from the low level compiler which doesn't happen. If one sees unexpected, significant slowdowns, these should be reported.

I also have results in a larger set of forms if interested.

**Comment by FabioLuporini** [comment]
As for the config on Archer: it depends on the compiler used and what sort of machines one is running on. 

export PYOP2_BACKEND_COMPILER={intel, gnu}
export PYOP2_SIMD_ISA={sse, avx}

these are two key flags. If you are running on avx machines with gcc, I recommend to set

export PYOP2_BACKEND_COMPILER=gnu
export PYOP2_SIMD_ISA=avx

**Comment by dorugeber** [comment]
-would you recommend using the Intel compiler instead?  (pretty sure ARCHER has Cray/Intel/GCC)

**Comment by FabioLuporini** [comment]
In my experience cray/intel >(>>) gcc. For a simple reason: they manage to vectorise small (easily vectorisable) loops. 

Said that, I haven't played with recent versions of gcc, so maybe things have changed, though I doubt

**Comment by dorugeber** [comment]
Okay, cool.  IIRC, Eike's comparing the 'normal' assemble-solve approach with matrix-free (pure assembly) and other variants, so the results are meaningless unless assembly (mostly one-form assembly, I guess) is being done as efficiently as possible.

**Comment by FabioLuporini** [comment]
Now fixed, so closing.
